"""added scalablity + Auth + Ownership + Leadcontact

Revision ID: 4c2d31e19f4b
Revises: b979154befdd
Create Date: 2025-12-25 05:41:20.329689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2d31e19f4b'
down_revision: Union[str, None] = 'b979154befdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
