"""add lead ownership and Auth and CRUD

Revision ID: c73f7b598fe7
Revises: 2612827d8ebc
Create Date: 2025-12-25 05:11:09.910460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73f7b598fe7'
down_revision: Union[str, None] = '2612827d8ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('agents', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'agents', ['email'])
    op.add_column('leads', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'leads', 'agents', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'created_by_id')
    op.drop_column('leads', 'phone_number')
    op.drop_constraint(None, 'agents', type_='unique')
    op.drop_column('agents', 'hashed_password')
    op.drop_column('agents', 'email')
    # ### end Alembic commands ###
